default: &default
  adapter: postgresql
  encoding: utf8
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000


development:
  <<: *default
  database: chat-feature-dev

test:
  <<: *default
  database: chat-feature-test

staging:
  <<: *default
  database: chat-feature-staging
  

production:
  <<: *default
  database: chat-feature-live
  
